// <auto-generated />
using System;
using Campus_Cart_Student_Marketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campus_Cart_Student_Marketplace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616215823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Listings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seller")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "School Supplies"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dorm Essentials"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable ergonomic office chair.",
                            ImageUrl = "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 100000m,
                            SellerId = "student1",
                            Title = "Belleze Ergonomic Chair"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spacious wooden study desk.",
                            ImageUrl = "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 85000m,
                            SellerId = "student2",
                            Title = "Study Desk"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adjustable gaming chair.",
                            ImageUrl = "https://images.unsplash.com/photo-1598550476439-6847785fce6e?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 120000m,
                            SellerId = "student3",
                            Title = "Gaming Chair"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5-tier bookshelf.",
                            ImageUrl = "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 45000m,
                            SellerId = "student4",
                            Title = "Bookshelf"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LED study lamp.",
                            ImageUrl = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 10000m,
                            SellerId = "student14",
                            Title = "Desk Lamp"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable office chair.",
                            ImageUrl = "https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 70000m,
                            SellerId = "student15",
                            Title = "Office Chair"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Single-size bed frame.",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 65000m,
                            SellerId = "student16",
                            Title = "Bed Frame"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Single mattress.",
                            ImageUrl = "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 50000m,
                            SellerId = "student17",
                            Title = "Mattress"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Simple study chair.",
                            ImageUrl = "https://images.unsplash.com/photo-1562184552-997c461abbe6?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 30000m,
                            SellerId = "student31",
                            Title = "Study Chair"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft floor rug.",
                            ImageUrl = "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 14000m,
                            SellerId = "student39",
                            Title = "Dorm Rug"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Large plastic storage bin.",
                            ImageUrl = "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 10000m,
                            SellerId = "student40",
                            Title = "Storage Bin"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact dorm fridge.",
                            ImageUrl = "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 95000m,
                            SellerId = "student5",
                            Title = "Mini Fridge"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "700W microwave.",
                            ImageUrl = "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 55000m,
                            SellerId = "student6",
                            Title = "Microwave Oven"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4-outlet extension cord.",
                            ImageUrl = "https://images.unsplash.com/photo-1558538337-aab544368de8?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 7000m,
                            SellerId = "student28",
                            Title = "Extension Cord"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Single-cup coffee maker.",
                            ImageUrl = "https://images.unsplash.com/photo-1517256064527-09c53b2d0c6b?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 25000m,
                            SellerId = "student29",
                            Title = "Coffee Maker"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fast-boil kettle.",
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 18000m,
                            SellerId = "student30",
                            Title = "Electric Kettle"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable fan.",
                            ImageUrl = "https://images.unsplash.com/photo-1618945032343-340a62a13be5?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 11000m,
                            SellerId = "student35",
                            Title = "Portable Fan"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aluminum adjustable stand.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 15000m,
                            SellerId = "student7",
                            Title = "Laptop Stand"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB mechanical keyboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 35000m,
                            SellerId = "student8",
                            Title = "Mechanical Keyboard"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bluetooth mouse.",
                            ImageUrl = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 12000m,
                            SellerId = "student9",
                            Title = "Wireless Mouse"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full HD monitor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 80000m,
                            SellerId = "student10",
                            Title = "24 Inch Monitor"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless printer.",
                            ImageUrl = "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 45000m,
                            SellerId = "student18",
                            Title = "Printer"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable SSD storage.",
                            ImageUrl = "https://images.unsplash.com/photo-1601524909162-be87252be298?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 30000m,
                            SellerId = "student19",
                            Title = "External SSD 500GB"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HD webcam for meetings.",
                            ImageUrl = "https://images.unsplash.com/photo-1603184017968-945045663bd4?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 18000m,
                            SellerId = "student20",
                            Title = "1080p Webcam"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable speaker.",
                            ImageUrl = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 25000m,
                            SellerId = "student21",
                            Title = "Bluetooth Speaker"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise-cancelling headphones.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 40000m,
                            SellerId = "student22",
                            Title = "Headphones"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed Wi-Fi router.",
                            ImageUrl = "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 28000m,
                            SellerId = "student23",
                            Title = "Wi-Fi Router"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "20,000mAh power bank.",
                            ImageUrl = "https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 22000m,
                            SellerId = "student27",
                            Title = "Power Bank"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7-port USB hub.",
                            ImageUrl = "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 8000m,
                            SellerId = "student33",
                            Title = "USB Hub"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adjustable stand.",
                            ImageUrl = "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 9000m,
                            SellerId = "student36",
                            Title = "Tablet Stand"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mini HD projector.",
                            ImageUrl = "https://images.unsplash.com/photo-1535016120720-40c646be5580?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 95000m,
                            SellerId = "student38",
                            Title = "Portable Projector"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "University calculus textbook.",
                            ImageUrl = "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 18000m,
                            SellerId = "student11",
                            Title = "Calculus Textbook"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introductory physics textbook.",
                            ImageUrl = "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 22000m,
                            SellerId = "student12",
                            Title = "Physics Textbook"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basic chemistry kit.",
                            ImageUrl = "https://images.unsplash.com/photo-1532187863486-abf9d39d6618?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 25000m,
                            SellerId = "student13",
                            Title = "Chemistry Lab Kit"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Condition = "Used",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Student scientific calculator.",
                            ImageUrl = "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 9000m,
                            SellerId = "student24",
                            Title = "Scientific Calculator"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Condition = "Like New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable whiteboard.",
                            ImageUrl = "https://images.unsplash.com/photo-1611224885990-ab7363d12259?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 15000m,
                            SellerId = "student32",
                            Title = "Whiteboard"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Large student backpack.",
                            ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 12000m,
                            SellerId = "student25",
                            Title = "Backpack"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Insulated bottle.",
                            ImageUrl = "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 5000m,
                            SellerId = "student26",
                            Title = "Water Bottle"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Condition = "Good",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-compartment organizer.",
                            ImageUrl = "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 6000m,
                            SellerId = "student34",
                            Title = "Desk Organizer"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Condition = "New",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dorm room lights.",
                            ImageUrl = "https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=500&auto=format&fit=crop&q=60",
                            IsAvailable = true,
                            Price = 12000m,
                            SellerId = "student37",
                            Title = "LED Strip Lights"
                        });
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.CartItem", b =>
                {
                    b.HasOne("Campus_Cart_Student_Marketplace.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Campus_Cart_Student_Marketplace.Models.Message", b =>
                {
                    b.HasOne("Campus_Cart_Student_Marketplace.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Campus_Cart_Student_Marketplace.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Campus_Cart_Student_Marketplace.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Campus_Cart_Student_Marketplace.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Campus_Cart_Student_Marketplace.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
